# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'avr_pin_configurator.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import sys
import xml.etree.ElementTree as ET
import os, stat
from datetime import date


class Ui_Form(object):
    listOfRadios = list(list(list()))
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1079, 748)
        Form.setMaximumSize(QSize(1079, 748))
        self.portsForm = QToolBox(Form)
        self.portsForm.setObjectName(u"portsForm")
        self.portsForm.setGeometry(QRect(-2, -3, 1091, 750))
        font = QFont()
        font.setPointSize(10)
        self.portsForm.setFont(font)
        self.portsForm.setCursor(QCursor(Qt.ArrowCursor))
        self.portsForm.setStyleSheet(u"QWidget{\n"
            "color: rgb(255, 255, 255);\n"
            "background-color: rgb(0, 0, 0);\n"
            "border-color: rgb(255, 255, 255);\n"
            "selection-background-color: rgb(85, 0, 0);\n"
            "border-style: outset;\n"
            "border-width: 2px;\n"
            "border-radius: 10px;\n"
            "border-color: rgb(255, 255, 255);\n"
            "}\n"
            "QRadioButton{\n"
            "border: none;\n"
            "}\n"
            "QRadioButton::indicator::unchecked{ \n"
            "border: 1px solid; \n"
            "border-color: rgb(255, 85, 0);\n"
            "border-radius: 5px;\n"
            "background-color: rgb(255, 85, 0); \n"
            "width: 11px; \n"
            "height: 11px; \n"
            "}\n"
            "\n"
            "QRadioButton::indicator::checked{ \n"
            "border: 3px solid; \n"
            "border-color: white;\n"
            "border-radius: 6px;\n"
            "background-color: rgb(85, 85, 255); \n"
            "width: 7px; \n"
            "height: 7px; \n"
            "}\n"
            "QPushButton{\n"
            "	color: rgb(0, 0, 0);\n"
            "	background-color: rgb(255, 255, 0);\n"
            "	selection-background-color: rgb(170, 85, 0);\n"
            "	selection-color: rgb(255, 0, 0);\n"
            "	border-style: outset;\n"
            "	border-width: 2px;\n"
            "	border-radius: 15px;\n"
            "	border-color: white;\n"
            "}")
        self.portaPage = QWidget()
        self.portaPage.setObjectName(u"portaPage")
        self.portaPage.setGeometry(QRect(0, 0, 1083, 598))
        self.portaPin0Box = QGroupBox(self.portaPage)
        self.portaPin0Box.setObjectName(u"portaPin0Box")
        self.portaPin0Box.setGeometry(QRect(60, 30, 191, 211))
        font1 = QFont()
        font1.setPointSize(12)
        self.portaPin0Box.setFont(font1)
        self.portaPin0OutputLowRadio = QRadioButton(self.portaPin0Box)
        self.portaPin0OutputLowRadio.setObjectName(u"portaPin0OutputLowRadio")
        self.portaPin0OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portaPin0OutputLowRadio.setFont(font)
        self.portaPin0InputHighImpRadio = QRadioButton(self.portaPin0Box)
        self.portaPin0InputHighImpRadio.setObjectName(u"portaPin0InputHighImpRadio")
        self.portaPin0InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin0InputHighImpRadio.setFont(font)
        self.portaPin0InputPullRadio = QRadioButton(self.portaPin0Box)
        self.portaPin0InputPullRadio.setObjectName(u"portaPin0InputPullRadio")
        self.portaPin0InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin0InputPullRadio.setFont(font)
        self.portaPin0OutputHighRadio = QRadioButton(self.portaPin0Box)
        self.portaPin0OutputHighRadio.setObjectName(u"portaPin0OutputHighRadio")
        self.portaPin0OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portaPin0OutputHighRadio.setFont(font)
        self.portaPin1Box = QGroupBox(self.portaPage)
        self.portaPin1Box.setObjectName(u"portaPin1Box")
        self.portaPin1Box.setGeometry(QRect(320, 30, 191, 211))
        self.portaPin1Box.setFont(font1)
        self.portaPin1OutputLowRadio = QRadioButton(self.portaPin1Box)
        self.portaPin1OutputLowRadio.setObjectName(u"portaPin1OutputLowRadio")
        self.portaPin1OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portaPin1OutputLowRadio.setFont(font)
        self.portaPin1InputHighImpRadio = QRadioButton(self.portaPin1Box)
        self.portaPin1InputHighImpRadio.setObjectName(u"portaPin1InputHighImpRadio")
        self.portaPin1InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin1InputHighImpRadio.setFont(font)
        self.portaPin1InputPullRadio = QRadioButton(self.portaPin1Box)
        self.portaPin1InputPullRadio.setObjectName(u"portaPin1InputPullRadio")
        self.portaPin1InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin1InputPullRadio.setFont(font)
        self.portaPin1OutputHighRadio = QRadioButton(self.portaPin1Box)
        self.portaPin1OutputHighRadio.setObjectName(u"portaPin1OutputHighRadio")
        self.portaPin1OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portaPin1OutputHighRadio.setFont(font)
        self.portaPin2Box = QGroupBox(self.portaPage)
        self.portaPin2Box.setObjectName(u"portaPin2Box")
        self.portaPin2Box.setGeometry(QRect(580, 30, 191, 211))
        self.portaPin2Box.setFont(font1)
        self.portaPin2OutputLowRadio = QRadioButton(self.portaPin2Box)
        self.portaPin2OutputLowRadio.setObjectName(u"portaPin2OutputLowRadio")
        self.portaPin2OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portaPin2OutputLowRadio.setFont(font)
        self.portaPin2InputHighImpRadio = QRadioButton(self.portaPin2Box)
        self.portaPin2InputHighImpRadio.setObjectName(u"portaPin2InputHighImpRadio")
        self.portaPin2InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin2InputHighImpRadio.setFont(font)
        self.portaPin2InputPullRadio = QRadioButton(self.portaPin2Box)
        self.portaPin2InputPullRadio.setObjectName(u"portaPin2InputPullRadio")
        self.portaPin2InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin2InputPullRadio.setFont(font)
        self.portaPin2OutputHighRadio = QRadioButton(self.portaPin2Box)
        self.portaPin2OutputHighRadio.setObjectName(u"portaPin2OutputHighRadio")
        self.portaPin2OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portaPin2OutputHighRadio.setFont(font)
        self.portaPin3Box = QGroupBox(self.portaPage)
        self.portaPin3Box.setObjectName(u"portaPin3Box")
        self.portaPin3Box.setGeometry(QRect(830, 30, 191, 211))
        self.portaPin3Box.setFont(font1)
        self.portaPin3OutputLowRadio = QRadioButton(self.portaPin3Box)
        self.portaPin3OutputLowRadio.setObjectName(u"portaPin3OutputLowRadio")
        self.portaPin3OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portaPin3OutputLowRadio.setFont(font)
        self.portaPin3InputHighImpRadio = QRadioButton(self.portaPin3Box)
        self.portaPin3InputHighImpRadio.setObjectName(u"portaPin3InputHighImpRadio")
        self.portaPin3InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin3InputHighImpRadio.setFont(font)
        self.portaPin3InputPullRadio = QRadioButton(self.portaPin3Box)
        self.portaPin3InputPullRadio.setObjectName(u"portaPin3InputPullRadio")
        self.portaPin3InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin3InputPullRadio.setFont(font)
        self.portaPin3OutputHighRadio = QRadioButton(self.portaPin3Box)
        self.portaPin3OutputHighRadio.setObjectName(u"portaPin3OutputHighRadio")
        self.portaPin3OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portaPin3OutputHighRadio.setFont(font)
        self.portaPin7Box = QGroupBox(self.portaPage)
        self.portaPin7Box.setObjectName(u"portaPin7Box")
        self.portaPin7Box.setGeometry(QRect(830, 300, 191, 211))
        self.portaPin7Box.setFont(font1)
        self.portaPin7OutputLowRadio = QRadioButton(self.portaPin7Box)
        self.portaPin7OutputLowRadio.setObjectName(u"portaPin7OutputLowRadio")
        self.portaPin7OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portaPin7OutputLowRadio.setFont(font)
        self.portaPin7InputHighImpRadio = QRadioButton(self.portaPin7Box)
        self.portaPin7InputHighImpRadio.setObjectName(u"portaPin7InputHighImpRadio")
        self.portaPin7InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin7InputHighImpRadio.setFont(font)
        self.portaPin7InputPullRadio = QRadioButton(self.portaPin7Box)
        self.portaPin7InputPullRadio.setObjectName(u"portaPin7InputPullRadio")
        self.portaPin7InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin7InputPullRadio.setFont(font)
        self.portaPin7OutputHighRadio = QRadioButton(self.portaPin7Box)
        self.portaPin7OutputHighRadio.setObjectName(u"portaPin7OutputHighRadio")
        self.portaPin7OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portaPin7OutputHighRadio.setFont(font)
        self.portaPin4Box = QGroupBox(self.portaPage)
        self.portaPin4Box.setObjectName(u"portaPin4Box")
        self.portaPin4Box.setGeometry(QRect(60, 300, 191, 211))
        self.portaPin4Box.setFont(font1)
        self.portaPin4OutputLowRadio = QRadioButton(self.portaPin4Box)
        self.portaPin4OutputLowRadio.setObjectName(u"portaPin4OutputLowRadio")
        self.portaPin4OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portaPin4OutputLowRadio.setFont(font)
        self.portaPin4InputHighImpRadio = QRadioButton(self.portaPin4Box)
        self.portaPin4InputHighImpRadio.setObjectName(u"portaPin4InputHighImpRadio")
        self.portaPin4InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin4InputHighImpRadio.setFont(font)
        self.portaPin4InputPullRadio = QRadioButton(self.portaPin4Box)
        self.portaPin4InputPullRadio.setObjectName(u"portaPin4InputPullRadio")
        self.portaPin4InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin4InputPullRadio.setFont(font)
        self.portaPin4OutputHighRadio = QRadioButton(self.portaPin4Box)
        self.portaPin4OutputHighRadio.setObjectName(u"portaPin4OutputHighRadio")
        self.portaPin4OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portaPin4OutputHighRadio.setFont(font)
        self.portaPin6Box = QGroupBox(self.portaPage)
        self.portaPin6Box.setObjectName(u"portaPin6Box")
        self.portaPin6Box.setGeometry(QRect(580, 300, 191, 211))
        self.portaPin6Box.setFont(font1)
        self.portaPin6OutputLowRadio = QRadioButton(self.portaPin6Box)
        self.portaPin6OutputLowRadio.setObjectName(u"portaPin6OutputLowRadio")
        self.portaPin6OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portaPin6OutputLowRadio.setFont(font)
        self.portaPin6InputHighImpRadio = QRadioButton(self.portaPin6Box)
        self.portaPin6InputHighImpRadio.setObjectName(u"portaPin6InputHighImpRadio")
        self.portaPin6InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin6InputHighImpRadio.setFont(font)
        self.portaPin6InputPullRadio = QRadioButton(self.portaPin6Box)
        self.portaPin6InputPullRadio.setObjectName(u"portaPin6InputPullRadio")
        self.portaPin6InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin6InputPullRadio.setFont(font)
        self.portaPin6OutputHighRadio = QRadioButton(self.portaPin6Box)
        self.portaPin6OutputHighRadio.setObjectName(u"portaPin6OutputHighRadio")
        self.portaPin6OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portaPin6OutputHighRadio.setFont(font)
        self.portaPin5Box = QGroupBox(self.portaPage)
        self.portaPin5Box.setObjectName(u"portaPin5Box")
        self.portaPin5Box.setGeometry(QRect(320, 300, 191, 211))
        self.portaPin5Box.setFont(font1)
        self.portaPin5OutputLowRadio = QRadioButton(self.portaPin5Box)
        self.portaPin5OutputLowRadio.setObjectName(u"portaPin5OutputLowRadio")
        self.portaPin5OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portaPin5OutputLowRadio.setFont(font)
        self.portaPin5InputHighImpRadio = QRadioButton(self.portaPin5Box)
        self.portaPin5InputHighImpRadio.setObjectName(u"portaPin5InputHighImpRadio")
        self.portaPin5InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portaPin5InputHighImpRadio.setFont(font)
        self.portaPin5InputPullRadio = QRadioButton(self.portaPin5Box)
        self.portaPin5InputPullRadio.setObjectName(u"portaPin5InputPullRadio")
        self.portaPin5InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portaPin5InputPullRadio.setFont(font)
        self.portaPin5OutputHighRadio = QRadioButton(self.portaPin5Box)
        self.portaPin5OutputHighRadio.setObjectName(u"portaPin5OutputHighRadio")
        self.portaPin5OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portaPin5OutputHighRadio.setFont(font)
        self.portsForm.addItem(self.portaPage, u"PORTA")
        self.portbPage = QWidget()
        self.portbPage.setObjectName(u"portbPage")
        self.portbPage.setGeometry(QRect(0, 0, 1083, 598))
        self.portbPin5Box = QGroupBox(self.portbPage)
        self.portbPin5Box.setObjectName(u"portbPin5Box")
        self.portbPin5Box.setGeometry(QRect(320, 330, 191, 211))
        self.portbPin5Box.setFont(font1)
        self.portbPin5OutputLowRadio = QRadioButton(self.portbPin5Box)
        self.portbPin5OutputLowRadio.setObjectName(u"portbPin5OutputLowRadio")
        self.portbPin5OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin5OutputLowRadio.setFont(font)
        self.portbPin5InputHighImpRadio = QRadioButton(self.portbPin5Box)
        self.portbPin5InputHighImpRadio.setObjectName(u"portbPin5InputHighImpRadio")
        self.portbPin5InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin5InputHighImpRadio.setFont(font)
        self.portbPin5InputPullRadio = QRadioButton(self.portbPin5Box)
        self.portbPin5InputPullRadio.setObjectName(u"portbPin5InputPullRadio")
        self.portbPin5InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin5InputPullRadio.setFont(font)
        self.portbPin5OutputHighRadio = QRadioButton(self.portbPin5Box)
        self.portbPin5OutputHighRadio.setObjectName(u"portbPin5OutputHighRadio")
        self.portbPin5OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portbPin5OutputHighRadio.setFont(font)
        self.portbPin2Box = QGroupBox(self.portbPage)
        self.portbPin2Box.setObjectName(u"portbPin2Box")
        self.portbPin2Box.setGeometry(QRect(580, 60, 191, 211))
        self.portbPin2Box.setFont(font1)
        self.portbPin2OutputLowRadio = QRadioButton(self.portbPin2Box)
        self.portbPin2OutputLowRadio.setObjectName(u"portbPin2OutputLowRadio")
        self.portbPin2OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin2OutputLowRadio.setFont(font)
        self.portbPin2InputHighImpRadio = QRadioButton(self.portbPin2Box)
        self.portbPin2InputHighImpRadio.setObjectName(u"portbPin2InputHighImpRadio")
        self.portbPin2InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin2InputHighImpRadio.setFont(font)
        self.portbPin2InputPullRadio = QRadioButton(self.portbPin2Box)
        self.portbPin2InputPullRadio.setObjectName(u"portbPin2InputPullRadio")
        self.portbPin2InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin2InputPullRadio.setFont(font)
        self.portbPin2OutputHighRadio = QRadioButton(self.portbPin2Box)
        self.portbPin2OutputHighRadio.setObjectName(u"portbPin2OutputHighRadio")
        self.portbPin2OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portbPin2OutputHighRadio.setFont(font)
        self.portbPin7Box = QGroupBox(self.portbPage)
        self.portbPin7Box.setObjectName(u"portbPin7Box")
        self.portbPin7Box.setGeometry(QRect(830, 330, 191, 211))
        self.portbPin7Box.setFont(font1)
        self.portbPin7OutputLowRadio = QRadioButton(self.portbPin7Box)
        self.portbPin7OutputLowRadio.setObjectName(u"portbPin7OutputLowRadio")
        self.portbPin7OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portbPin7OutputLowRadio.setFont(font)
        self.portbPin7InputHighImpRadio = QRadioButton(self.portbPin7Box)
        self.portbPin7InputHighImpRadio.setObjectName(u"portbPin7InputHighImpRadio")
        self.portbPin7InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin7InputHighImpRadio.setFont(font)
        self.portbPin7InputPullRadio = QRadioButton(self.portbPin7Box)
        self.portbPin7InputPullRadio.setObjectName(u"portbPin7InputPullRadio")
        self.portbPin7InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin7InputPullRadio.setFont(font)
        self.portbPin7OutputHighRadio = QRadioButton(self.portbPin7Box)
        self.portbPin7OutputHighRadio.setObjectName(u"portbPin7OutputHighRadio")
        self.portbPin7OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portbPin7OutputHighRadio.setFont(font)
        self.portbPin6Box = QGroupBox(self.portbPage)
        self.portbPin6Box.setObjectName(u"portbPin6Box")
        self.portbPin6Box.setGeometry(QRect(580, 330, 191, 211))
        self.portbPin6Box.setFont(font1)
        self.portbPin6OutputLowRadio = QRadioButton(self.portbPin6Box)
        self.portbPin6OutputLowRadio.setObjectName(u"portbPin6OutputLowRadio")
        self.portbPin6OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin6OutputLowRadio.setFont(font)
        self.portbPin6InputHighImpRadio = QRadioButton(self.portbPin6Box)
        self.portbPin6InputHighImpRadio.setObjectName(u"portbPin6InputHighImpRadio")
        self.portbPin6InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin6InputHighImpRadio.setFont(font)
        self.portbPin6InputPullRadio = QRadioButton(self.portbPin6Box)
        self.portbPin6InputPullRadio.setObjectName(u"portbPin6InputPullRadio")
        self.portbPin6InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin6InputPullRadio.setFont(font)
        self.portbPin6OutputHighRadio = QRadioButton(self.portbPin6Box)
        self.portbPin6OutputHighRadio.setObjectName(u"portbPin6OutputHighRadio")
        self.portbPin6OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portbPin6OutputHighRadio.setFont(font)
        self.portbPin4Box = QGroupBox(self.portbPage)
        self.portbPin4Box.setObjectName(u"portbPin4Box")
        self.portbPin4Box.setGeometry(QRect(60, 330, 191, 211))
        self.portbPin4Box.setFont(font1)
        self.portbPin4OutputLowRadio = QRadioButton(self.portbPin4Box)
        self.portbPin4OutputLowRadio.setObjectName(u"portbPin4OutputLowRadio")
        self.portbPin4OutputLowRadio.setGeometry(QRect(30, 80, 141, 20))
        self.portbPin4OutputLowRadio.setFont(font)
        self.portbPin4InputHighImpRadio = QRadioButton(self.portbPin4Box)
        self.portbPin4InputHighImpRadio.setObjectName(u"portbPin4InputHighImpRadio")
        self.portbPin4InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin4InputHighImpRadio.setFont(font)
        self.portbPin4InputPullRadio = QRadioButton(self.portbPin4Box)
        self.portbPin4InputPullRadio.setObjectName(u"portbPin4InputPullRadio")
        self.portbPin4InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin4InputPullRadio.setFont(font)
        self.portbPin4OutputHighRadio = QRadioButton(self.portbPin4Box)
        self.portbPin4OutputHighRadio.setObjectName(u"portbPin4OutputHighRadio")
        self.portbPin4OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portbPin4OutputHighRadio.setFont(font)
        self.portbPin3Box = QGroupBox(self.portbPage)
        self.portbPin3Box.setObjectName(u"portbPin3Box")
        self.portbPin3Box.setGeometry(QRect(830, 60, 191, 211))
        self.portbPin3Box.setFont(font1)
        self.portbPin3OutputLowRadio = QRadioButton(self.portbPin3Box)
        self.portbPin3OutputLowRadio.setObjectName(u"portbPin3OutputLowRadio")
        self.portbPin3OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin3OutputLowRadio.setFont(font)
        self.portbPin3InputHighImpRadio = QRadioButton(self.portbPin3Box)
        self.portbPin3InputHighImpRadio.setObjectName(u"portbPin3InputHighImpRadio")
        self.portbPin3InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin3InputHighImpRadio.setFont(font)
        self.portbPin3InputPullRadio = QRadioButton(self.portbPin3Box)
        self.portbPin3InputPullRadio.setObjectName(u"portbPin3InputPullRadio")
        self.portbPin3InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin3InputPullRadio.setFont(font)
        self.portbPin3OutputHighRadio = QRadioButton(self.portbPin3Box)
        self.portbPin3OutputHighRadio.setObjectName(u"portbPin3OutputHighRadio")
        self.portbPin3OutputHighRadio.setGeometry(QRect(30, 40, 141, 20))
        self.portbPin3OutputHighRadio.setFont(font)
        self.portbPin0Box = QGroupBox(self.portbPage)
        self.portbPin0Box.setObjectName(u"portbPin0Box")
        self.portbPin0Box.setGeometry(QRect(60, 60, 191, 211))
        self.portbPin0Box.setFont(font1)
        self.portbPin0OutputLowRadio = QRadioButton(self.portbPin0Box)
        self.portbPin0OutputLowRadio.setObjectName(u"portbPin0OutputLowRadio")
        self.portbPin0OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin0OutputLowRadio.setFont(font)
        self.portbPin0InputHighImpRadio = QRadioButton(self.portbPin0Box)
        self.portbPin0InputHighImpRadio.setObjectName(u"portbPin0InputHighImpRadio")
        self.portbPin0InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin0InputHighImpRadio.setFont(font)
        self.portbPin0InputPullRadio = QRadioButton(self.portbPin0Box)
        self.portbPin0InputPullRadio.setObjectName(u"portbPin0InputPullRadio")
        self.portbPin0InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin0InputPullRadio.setFont(font)
        self.portbPin0OutputHighRadio = QRadioButton(self.portbPin0Box)
        self.portbPin0OutputHighRadio.setObjectName(u"portbPin0OutputHighRadio")
        self.portbPin0OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portbPin0OutputHighRadio.setFont(font)
        self.portbPin1Box = QGroupBox(self.portbPage)
        self.portbPin1Box.setObjectName(u"portbPin1Box")
        self.portbPin1Box.setGeometry(QRect(320, 60, 191, 211))
        self.portbPin1Box.setFont(font1)
        self.portbPin1OutputLowRadio = QRadioButton(self.portbPin1Box)
        self.portbPin1OutputLowRadio.setObjectName(u"portbPin1OutputLowRadio")
        self.portbPin1OutputLowRadio.setGeometry(QRect(30, 80, 131, 20))
        self.portbPin1OutputLowRadio.setFont(font)
        self.portbPin1InputHighImpRadio = QRadioButton(self.portbPin1Box)
        self.portbPin1InputHighImpRadio.setObjectName(u"portbPin1InputHighImpRadio")
        self.portbPin1InputHighImpRadio.setGeometry(QRect(30, 120, 151, 20))
        self.portbPin1InputHighImpRadio.setFont(font)
        self.portbPin1InputPullRadio = QRadioButton(self.portbPin1Box)
        self.portbPin1InputPullRadio.setObjectName(u"portbPin1InputPullRadio")
        self.portbPin1InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portbPin1InputPullRadio.setFont(font)
        self.portbPin1OutputHighRadio = QRadioButton(self.portbPin1Box)
        self.portbPin1OutputHighRadio.setObjectName(u"portbPin1OutputHighRadio")
        self.portbPin1OutputHighRadio.setGeometry(QRect(30, 40, 131, 20))
        self.portbPin1OutputHighRadio.setFont(font)
        self.portsForm.addItem(self.portbPage, u"PORTB")
        self.portcPage = QWidget()
        self.portcPage.setObjectName(u"portcPage")
        self.portcPage.setGeometry(QRect(0, 0, 1083, 598))
        self.portcPin1Box = QGroupBox(self.portcPage)
        self.portcPin1Box.setObjectName(u"portcPin1Box")
        self.portcPin1Box.setGeometry(QRect(320, 60, 191, 211))
        self.portcPin1Box.setFont(font1)
        self.portcPin1OutputLowRadio = QRadioButton(self.portcPin1Box)
        self.portcPin1OutputLowRadio.setObjectName(u"portcPin1OutputLowRadio")
        self.portcPin1OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin1OutputLowRadio.setFont(font)
        self.portcPin1InputHighImpRadio = QRadioButton(self.portcPin1Box)
        self.portcPin1InputHighImpRadio.setObjectName(u"portcPin1InputHighImpRadio")
        self.portcPin1InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin1InputHighImpRadio.setFont(font)
        self.portcPin1InputPullRadio = QRadioButton(self.portcPin1Box)
        self.portcPin1InputPullRadio.setObjectName(u"portcPin1InputPullRadio")
        self.portcPin1InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin1InputPullRadio.setFont(font)
        self.portcPin1OutputHighRadio = QRadioButton(self.portcPin1Box)
        self.portcPin1OutputHighRadio.setObjectName(u"portcPin1OutputHighRadio")
        self.portcPin1OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin1OutputHighRadio.setFont(font)
        self.portcPin4Box = QGroupBox(self.portcPage)
        self.portcPin4Box.setObjectName(u"portcPin4Box")
        self.portcPin4Box.setGeometry(QRect(60, 330, 191, 211))
        self.portcPin4Box.setFont(font1)
        self.portcPin4OutputLowRadio = QRadioButton(self.portcPin4Box)
        self.portcPin4OutputLowRadio.setObjectName(u"portcPin4OutputLowRadio")
        self.portcPin4OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin4OutputLowRadio.setFont(font)
        self.portcPin4InputHighImpRadio = QRadioButton(self.portcPin4Box)
        self.portcPin4InputHighImpRadio.setObjectName(u"portcPin4InputHighImpRadio")
        self.portcPin4InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin4InputHighImpRadio.setFont(font)
        self.portcPin4InputPullRadio = QRadioButton(self.portcPin4Box)
        self.portcPin4InputPullRadio.setObjectName(u"portcPin4InputPullRadio")
        self.portcPin4InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin4InputPullRadio.setFont(font)
        self.portcPin4OutputHighRadio = QRadioButton(self.portcPin4Box)
        self.portcPin4OutputHighRadio.setObjectName(u"portcPin4OutputHighRadio")
        self.portcPin4OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin4OutputHighRadio.setFont(font)
        self.portcPin3Box = QGroupBox(self.portcPage)
        self.portcPin3Box.setObjectName(u"portcPin3Box")
        self.portcPin3Box.setGeometry(QRect(830, 60, 191, 211))
        self.portcPin3Box.setFont(font1)
        self.portcPin3OutputLowRadio = QRadioButton(self.portcPin3Box)
        self.portcPin3OutputLowRadio.setObjectName(u"portcPin3OutputLowRadio")
        self.portcPin3OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin3OutputLowRadio.setFont(font)
        self.portcPin3InputHighImpRadio = QRadioButton(self.portcPin3Box)
        self.portcPin3InputHighImpRadio.setObjectName(u"portcPin3InputHighImpRadio")
        self.portcPin3InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin3InputHighImpRadio.setFont(font)
        self.portcPin3InputPullRadio = QRadioButton(self.portcPin3Box)
        self.portcPin3InputPullRadio.setObjectName(u"portcPin3InputPullRadio")
        self.portcPin3InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin3InputPullRadio.setFont(font)
        self.portcPin3OutputHighRadio = QRadioButton(self.portcPin3Box)
        self.portcPin3OutputHighRadio.setObjectName(u"portcPin3OutputHighRadio")
        self.portcPin3OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin3OutputHighRadio.setFont(font)
        self.portcPin6Box = QGroupBox(self.portcPage)
        self.portcPin6Box.setObjectName(u"portcPin6Box")
        self.portcPin6Box.setGeometry(QRect(580, 330, 191, 211))
        self.portcPin6Box.setFont(font1)
        self.portcPin6OutputLowRadio = QRadioButton(self.portcPin6Box)
        self.portcPin6OutputLowRadio.setObjectName(u"portcPin6OutputLowRadio")
        self.portcPin6OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin6OutputLowRadio.setFont(font)
        self.portcPin6InputHighImpRadio = QRadioButton(self.portcPin6Box)
        self.portcPin6InputHighImpRadio.setObjectName(u"portcPin6InputHighImpRadio")
        self.portcPin6InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin6InputHighImpRadio.setFont(font)
        self.portcPin6InputPullRadio = QRadioButton(self.portcPin6Box)
        self.portcPin6InputPullRadio.setObjectName(u"portcPin6InputPullRadio")
        self.portcPin6InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin6InputPullRadio.setFont(font)
        self.portcPin6OutputHighRadio = QRadioButton(self.portcPin6Box)
        self.portcPin6OutputHighRadio.setObjectName(u"portcPin6OutputHighRadio")
        self.portcPin6OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin6OutputHighRadio.setFont(font)
        self.portcPin7Box = QGroupBox(self.portcPage)
        self.portcPin7Box.setObjectName(u"portcPin7Box")
        self.portcPin7Box.setGeometry(QRect(830, 330, 191, 211))
        self.portcPin7Box.setFont(font1)
        self.portcPin7OutputLowRadio = QRadioButton(self.portcPin7Box)
        self.portcPin7OutputLowRadio.setObjectName(u"portcPin7OutputLowRadio")
        self.portcPin7OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin7OutputLowRadio.setFont(font)
        self.portcPin7InputHighImpRadio = QRadioButton(self.portcPin7Box)
        self.portcPin7InputHighImpRadio.setObjectName(u"portcPin7InputHighImpRadio")
        self.portcPin7InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin7InputHighImpRadio.setFont(font)
        self.portcPin7InputPullRadio = QRadioButton(self.portcPin7Box)
        self.portcPin7InputPullRadio.setObjectName(u"portcPin7InputPullRadio")
        self.portcPin7InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin7InputPullRadio.setFont(font)
        self.portcPin7OutputHighRadio = QRadioButton(self.portcPin7Box)
        self.portcPin7OutputHighRadio.setObjectName(u"portcPin7OutputHighRadio")
        self.portcPin7OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin7OutputHighRadio.setFont(font)
        self.portcPin2Box = QGroupBox(self.portcPage)
        self.portcPin2Box.setObjectName(u"portcPin2Box")
        self.portcPin2Box.setGeometry(QRect(580, 60, 191, 211))
        self.portcPin2Box.setFont(font1)
        self.portcPin2OutputLowRadio = QRadioButton(self.portcPin2Box)
        self.portcPin2OutputLowRadio.setObjectName(u"portcPin2OutputLowRadio")
        self.portcPin2OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin2OutputLowRadio.setFont(font)
        self.portcPin2InputHighImpRadio = QRadioButton(self.portcPin2Box)
        self.portcPin2InputHighImpRadio.setObjectName(u"portcPin2InputHighImpRadio")
        self.portcPin2InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin2InputHighImpRadio.setFont(font)
        self.portcPin2InputPullRadio = QRadioButton(self.portcPin2Box)
        self.portcPin2InputPullRadio.setObjectName(u"portcPin2InputPullRadio")
        self.portcPin2InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin2InputPullRadio.setFont(font)
        self.portcPin2OutputHighRadio = QRadioButton(self.portcPin2Box)
        self.portcPin2OutputHighRadio.setObjectName(u"portcPin2OutputHighRadio")
        self.portcPin2OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin2OutputHighRadio.setFont(font)
        self.portcPin0Box = QGroupBox(self.portcPage)
        self.portcPin0Box.setObjectName(u"portcPin0Box")
        self.portcPin0Box.setGeometry(QRect(60, 60, 191, 211))
        self.portcPin0Box.setFont(font1)
        self.portcPin0OutputLowRadio = QRadioButton(self.portcPin0Box)
        self.portcPin0OutputLowRadio.setObjectName(u"portcPin0OutputLowRadio")
        self.portcPin0OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin0OutputLowRadio.setFont(font)
        self.portcPin0InputHighImpRadio = QRadioButton(self.portcPin0Box)
        self.portcPin0InputHighImpRadio.setObjectName(u"portcPin0InputHighImpRadio")
        self.portcPin0InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin0InputHighImpRadio.setFont(font)
        self.portcPin0InputPullRadio = QRadioButton(self.portcPin0Box)
        self.portcPin0InputPullRadio.setObjectName(u"portcPin0InputPullRadio")
        self.portcPin0InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin0InputPullRadio.setFont(font)
        self.portcPin0OutputHighRadio = QRadioButton(self.portcPin0Box)
        self.portcPin0OutputHighRadio.setObjectName(u"portcPin0OutputHighRadio")
        self.portcPin0OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin0OutputHighRadio.setFont(font)
        self.portcPin5Box = QGroupBox(self.portcPage)
        self.portcPin5Box.setObjectName(u"portcPin5Box")
        self.portcPin5Box.setGeometry(QRect(320, 330, 191, 211))
        self.portcPin5Box.setFont(font1)
        self.portcPin5OutputLowRadio = QRadioButton(self.portcPin5Box)
        self.portcPin5OutputLowRadio.setObjectName(u"portcPin5OutputLowRadio")
        self.portcPin5OutputLowRadio.setGeometry(QRect(30, 80, 130, 20))
        self.portcPin5OutputLowRadio.setFont(font)
        self.portcPin5InputHighImpRadio = QRadioButton(self.portcPin5Box)
        self.portcPin5InputHighImpRadio.setObjectName(u"portcPin5InputHighImpRadio")
        self.portcPin5InputHighImpRadio.setGeometry(QRect(30, 120, 147, 20))
        self.portcPin5InputHighImpRadio.setFont(font)
        self.portcPin5InputPullRadio = QRadioButton(self.portcPin5Box)
        self.portcPin5InputPullRadio.setObjectName(u"portcPin5InputPullRadio")
        self.portcPin5InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portcPin5InputPullRadio.setFont(font)
        self.portcPin5OutputHighRadio = QRadioButton(self.portcPin5Box)
        self.portcPin5OutputHighRadio.setObjectName(u"portcPin5OutputHighRadio")
        self.portcPin5OutputHighRadio.setGeometry(QRect(30, 40, 130, 20))
        self.portcPin5OutputHighRadio.setFont(font)
        self.portsForm.addItem(self.portcPage, u"PORTC")
        self.portdPage = QWidget()
        self.portdPage.setObjectName(u"portdPage")
        self.portdPage.setGeometry(QRect(0, 0, 1083, 598))
        self.btnLoad = QPushButton(self.portdPage)
        self.btnLoad.setObjectName(u"btnLoad")
        self.btnLoad.setGeometry(QRect(120, 530, 181, 41))
        font2 = QFont()
        font2.setPointSize(13)
        self.btnLoad.setFont(font2)
        self.btnLoad.setStyleSheet(u"")
        self.btnSave = QPushButton(self.portdPage)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(730, 530, 181, 41))
        self.btnSave.setFont(font2)
        self.btnSave.setStyleSheet(u"")
        self.portdPin5Box = QGroupBox(self.portdPage)
        self.portdPin5Box.setObjectName(u"portdPin5Box")
        self.portdPin5Box.setGeometry(QRect(320, 270, 191, 211))
        self.portdPin5Box.setFont(font1)
        self.portdPin5OutputLowRadio = QRadioButton(self.portdPin5Box)
        self.portdPin5OutputLowRadio.setObjectName(u"portdPin5OutputLowRadio")
        self.portdPin5OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin5OutputLowRadio.setFont(font)
        self.portdPin5InputHighImpRadio = QRadioButton(self.portdPin5Box)
        self.portdPin5InputHighImpRadio.setObjectName(u"portdPin5InputHighImpRadio")
        self.portdPin5InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin5InputHighImpRadio.setFont(font)
        self.portdPin5InputPullRadio = QRadioButton(self.portdPin5Box)
        self.portdPin5InputPullRadio.setObjectName(u"portdPin5InputPullRadio")
        self.portdPin5InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin5InputPullRadio.setFont(font)
        self.portdPin5OutputHighRadio = QRadioButton(self.portdPin5Box)
        self.portdPin5OutputHighRadio.setObjectName(u"portdPin5OutputHighRadio")
        self.portdPin5OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin5OutputHighRadio.setFont(font)
        self.portdPin4Box = QGroupBox(self.portdPage)
        self.portdPin4Box.setObjectName(u"portdPin4Box")
        self.portdPin4Box.setGeometry(QRect(60, 270, 191, 211))
        self.portdPin4Box.setFont(font1)
        self.portdPin4OutputLowRadio = QRadioButton(self.portdPin4Box)
        self.portdPin4OutputLowRadio.setObjectName(u"portdPin4OutputLowRadio")
        self.portdPin4OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin4OutputLowRadio.setFont(font)
        self.portdPin4InputHighImpRadio = QRadioButton(self.portdPin4Box)
        self.portdPin4InputHighImpRadio.setObjectName(u"portdPin4InputHighImpRadio")
        self.portdPin4InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin4InputHighImpRadio.setFont(font)
        self.portdPin4InputPullRadio = QRadioButton(self.portdPin4Box)
        self.portdPin4InputPullRadio.setObjectName(u"portdPin4InputPullRadio")
        self.portdPin4InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin4InputPullRadio.setFont(font)
        self.portdPin4OutputHighRadio = QRadioButton(self.portdPin4Box)
        self.portdPin4OutputHighRadio.setObjectName(u"portdPin4OutputHighRadio")
        self.portdPin4OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin4OutputHighRadio.setFont(font)
        self.portdPin3Box = QGroupBox(self.portdPage)
        self.portdPin3Box.setObjectName(u"portdPin3Box")
        self.portdPin3Box.setGeometry(QRect(830, 20, 191, 211))
        self.portdPin3Box.setFont(font1)
        self.portdPin3OutputLowRadio = QRadioButton(self.portdPin3Box)
        self.portdPin3OutputLowRadio.setObjectName(u"portdPin3OutputLowRadio")
        self.portdPin3OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin3OutputLowRadio.setFont(font)
        self.portdPin3OutputLowRadio.setCheckable(True)
        self.portdPin3InputHighImpRadio = QRadioButton(self.portdPin3Box)
        self.portdPin3InputHighImpRadio.setObjectName(u"portdPin3InputHighImpRadio")
        self.portdPin3InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin3InputHighImpRadio.setFont(font)
        self.portdPin3InputPullRadio = QRadioButton(self.portdPin3Box)
        self.portdPin3InputPullRadio.setObjectName(u"portdPin3InputPullRadio")
        self.portdPin3InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin3InputPullRadio.setFont(font)
        self.portdPin3OutputHighRadio = QRadioButton(self.portdPin3Box)
        self.portdPin3OutputHighRadio.setObjectName(u"portdPin3OutputHighRadio")
        self.portdPin3OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin3OutputHighRadio.setFont(font)
        self.portdPin3OutputHighRadio.setCheckable(True)
        self.portdPin0Box = QGroupBox(self.portdPage)
        self.portdPin0Box.setObjectName(u"portdPin0Box")
        self.portdPin0Box.setGeometry(QRect(60, 20, 191, 211))
        self.portdPin0Box.setFont(font1)
        self.portdPin0Box.setStyleSheet(u"")
        self.portdPin0OutputLowRadio = QRadioButton(self.portdPin0Box)
        self.portdPin0OutputLowRadio.setObjectName(u"portdPin0OutputLowRadio")
        self.portdPin0OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin0OutputLowRadio.setFont(font)
        self.portdPin0InputHighImpRadio = QRadioButton(self.portdPin0Box)
        self.portdPin0InputHighImpRadio.setObjectName(u"portdPin0InputHighImpRadio")
        self.portdPin0InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin0InputHighImpRadio.setFont(font)
        self.portdPin0InputPullRadio = QRadioButton(self.portdPin0Box)
        self.portdPin0InputPullRadio.setObjectName(u"portdPin0InputPullRadio")
        self.portdPin0InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin0InputPullRadio.setFont(font)
        self.portdPin0OutputHighRadio = QRadioButton(self.portdPin0Box)
        self.portdPin0OutputHighRadio.setObjectName(u"portdPin0OutputHighRadio")
        self.portdPin0OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin0OutputHighRadio.setFont(font)
        self.portdPin1Box = QGroupBox(self.portdPage)
        self.portdPin1Box.setObjectName(u"portdPin1Box")
        self.portdPin1Box.setGeometry(QRect(320, 20, 191, 211))
        self.portdPin1Box.setFont(font1)
        self.portdPin1OutputLowRadio = QRadioButton(self.portdPin1Box)
        self.portdPin1OutputLowRadio.setObjectName(u"portdPin1OutputLowRadio")
        self.portdPin1OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin1OutputLowRadio.setFont(font)
        self.portdPin1InputHighImpRadio = QRadioButton(self.portdPin1Box)
        self.portdPin1InputHighImpRadio.setObjectName(u"portdPin1InputHighImpRadio")
        self.portdPin1InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin1InputHighImpRadio.setFont(font)
        self.portdPin1InputPullRadio = QRadioButton(self.portdPin1Box)
        self.portdPin1InputPullRadio.setObjectName(u"portdPin1InputPullRadio")
        self.portdPin1InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin1InputPullRadio.setFont(font)
        self.portdPin1OutputHighRadio = QRadioButton(self.portdPin1Box)
        self.portdPin1OutputHighRadio.setObjectName(u"portdPin1OutputHighRadio")
        self.portdPin1OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin1OutputHighRadio.setFont(font)
        self.portdPin7Box = QGroupBox(self.portdPage)
        self.portdPin7Box.setObjectName(u"portdPin7Box")
        self.portdPin7Box.setGeometry(QRect(830, 270, 191, 211))
        self.portdPin7Box.setFont(font1)
        self.portdPin7OutputLowRadio = QRadioButton(self.portdPin7Box)
        self.portdPin7OutputLowRadio.setObjectName(u"portdPin7OutputLowRadio")
        self.portdPin7OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin7OutputLowRadio.setFont(font)
        self.portdPin7InputHighImpRadio = QRadioButton(self.portdPin7Box)
        self.portdPin7InputHighImpRadio.setObjectName(u"portdPin7InputHighImpRadio")
        self.portdPin7InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin7InputHighImpRadio.setFont(font)
        self.portdPin7InputPullRadio = QRadioButton(self.portdPin7Box)
        self.portdPin7InputPullRadio.setObjectName(u"portdPin7InputPullRadio")
        self.portdPin7InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin7InputPullRadio.setFont(font)
        self.portdPin7OutputHighRadio = QRadioButton(self.portdPin7Box)
        self.portdPin7OutputHighRadio.setObjectName(u"portdPin7OutputHighRadio")
        self.portdPin7OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin7OutputHighRadio.setFont(font)
        self.portdPin6Box = QGroupBox(self.portdPage)
        self.portdPin6Box.setObjectName(u"portdPin6Box")
        self.portdPin6Box.setGeometry(QRect(580, 270, 191, 211))
        self.portdPin6Box.setFont(font1)
        self.portdPin6OutputLowRadio = QRadioButton(self.portdPin6Box)
        self.portdPin6OutputLowRadio.setObjectName(u"portdPin6OutputLowRadio")
        self.portdPin6OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin6OutputLowRadio.setFont(font)
        self.portdPin6InputHighImpRadio = QRadioButton(self.portdPin6Box)
        self.portdPin6InputHighImpRadio.setObjectName(u"portdPin6InputHighImpRadio")
        self.portdPin6InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin6InputHighImpRadio.setFont(font)
        self.portdPin6InputPullRadio = QRadioButton(self.portdPin6Box)
        self.portdPin6InputPullRadio.setObjectName(u"portdPin6InputPullRadio")
        self.portdPin6InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin6InputPullRadio.setFont(font)
        self.portdPin6OutputHighRadio = QRadioButton(self.portdPin6Box)
        self.portdPin6OutputHighRadio.setObjectName(u"portdPin6OutputHighRadio")
        self.portdPin6OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin6OutputHighRadio.setFont(font)
        self.portdPin2Box = QGroupBox(self.portdPage)
        self.portdPin2Box.setObjectName(u"portdPin2Box")
        self.portdPin2Box.setGeometry(QRect(580, 20, 191, 211))
        self.portdPin2Box.setFont(font1)
        self.portdPin2Box.setStyleSheet(u"")
        self.portdPin2OutputLowRadio = QRadioButton(self.portdPin2Box)
        self.portdPin2OutputLowRadio.setObjectName(u"portdPin2OutputLowRadio")
        self.portdPin2OutputLowRadio.setGeometry(QRect(30, 80, 140, 20))
        self.portdPin2OutputLowRadio.setFont(font)
        self.portdPin2InputHighImpRadio = QRadioButton(self.portdPin2Box)
        self.portdPin2InputHighImpRadio.setObjectName(u"portdPin2InputHighImpRadio")
        self.portdPin2InputHighImpRadio.setGeometry(QRect(30, 120, 148, 20))
        self.portdPin2InputHighImpRadio.setFont(font)
        self.portdPin2InputPullRadio = QRadioButton(self.portdPin2Box)
        self.portdPin2InputPullRadio.setObjectName(u"portdPin2InputPullRadio")
        self.portdPin2InputPullRadio.setGeometry(QRect(30, 160, 141, 20))
        self.portdPin2InputPullRadio.setFont(font)
        self.portdPin2OutputHighRadio = QRadioButton(self.portdPin2Box)
        self.portdPin2OutputHighRadio.setObjectName(u"portdPin2OutputHighRadio")
        self.portdPin2OutputHighRadio.setGeometry(QRect(30, 40, 140, 20))
        self.portdPin2OutputHighRadio.setFont(font)
        self.btnGenerate = QPushButton(self.portdPage)
        self.btnGenerate.setObjectName(u"btnGenerate")
        self.btnGenerate.setGeometry(QRect(440, 530, 181, 41))
        self.btnGenerate.setFont(font2)
        self.btnGenerate.setStyleSheet(u"")
        self.portsForm.addItem(self.portdPage, u"PORTD")

        self.retranslateUi(Form)
        self.btnGenerate.clicked.connect(self.btnGenerateAction)
        self.btnLoad.clicked.connect(self.btnLoadConfigAction)
        self.btnSave.clicked.connect(self.btnSaveConfigAction)

        self.portsForm.setCurrentIndex(3)

        #list(listofports(listofpins(listofoptions)))
        #porta >> 0
        #portb >> 1
        #portc >> 2
        #portd >> 3

        #pins from 0 to 7, buttons: 0 (output high), 1 (output low), 2 (input hight imp), 3 (input pull up)

        #you want output high button in porta pin 3? write: self.listOfRadios[0][3][0]
        self.listOfRadios = [
            #PORTA
                [
                    [self.portaPin0OutputHighRadio, self.portaPin0OutputLowRadio, self.portaPin0InputHighImpRadio, self.portaPin0InputPullRadio],
                    [self.portaPin1OutputHighRadio, self.portaPin1OutputLowRadio, self.portaPin1InputHighImpRadio, self.portaPin1InputPullRadio],
                    [self.portaPin2OutputHighRadio, self.portaPin2OutputLowRadio, self.portaPin2InputHighImpRadio, self.portaPin2InputPullRadio],
                    [self.portaPin3OutputHighRadio, self.portaPin3OutputLowRadio, self.portaPin3InputHighImpRadio, self.portaPin3InputPullRadio],
                    [self.portaPin4OutputHighRadio, self.portaPin4OutputLowRadio, self.portaPin4InputHighImpRadio, self.portaPin4InputPullRadio],
                    [self.portaPin5OutputHighRadio, self.portaPin5OutputLowRadio, self.portaPin5InputHighImpRadio, self.portaPin5InputPullRadio],
                    [self.portaPin6OutputHighRadio, self.portaPin6OutputLowRadio, self.portaPin6InputHighImpRadio, self.portaPin6InputPullRadio],
                    [self.portaPin7OutputHighRadio, self.portaPin7OutputLowRadio, self.portaPin7InputHighImpRadio, self.portaPin7InputPullRadio]
                ],
            #PORTB
                [
                    [self.portbPin0OutputHighRadio, self.portbPin0OutputLowRadio, self.portbPin0InputHighImpRadio, self.portbPin0InputPullRadio],
                    [self.portbPin1OutputHighRadio, self.portbPin1OutputLowRadio, self.portbPin1InputHighImpRadio, self.portbPin1InputPullRadio],
                    [self.portbPin2OutputHighRadio, self.portbPin2OutputLowRadio, self.portbPin2InputHighImpRadio, self.portbPin2InputPullRadio],
                    [self.portbPin3OutputHighRadio, self.portbPin3OutputLowRadio, self.portbPin3InputHighImpRadio, self.portbPin3InputPullRadio],
                    [self.portbPin4OutputHighRadio, self.portbPin4OutputLowRadio, self.portbPin4InputHighImpRadio, self.portbPin4InputPullRadio],
                    [self.portbPin5OutputHighRadio, self.portbPin5OutputLowRadio, self.portbPin5InputHighImpRadio, self.portbPin5InputPullRadio],
                    [self.portbPin6OutputHighRadio, self.portbPin6OutputLowRadio, self.portbPin6InputHighImpRadio, self.portbPin6InputPullRadio],
                    [self.portbPin7OutputHighRadio, self.portbPin7OutputLowRadio, self.portbPin7InputHighImpRadio, self.portbPin7InputPullRadio]
                ],
            #PORTC
                [
                    [self.portcPin0OutputHighRadio, self.portcPin0OutputLowRadio, self.portcPin0InputHighImpRadio, self.portcPin0InputPullRadio],
                    [self.portcPin1OutputHighRadio, self.portcPin1OutputLowRadio, self.portcPin1InputHighImpRadio, self.portcPin1InputPullRadio],
                    [self.portcPin2OutputHighRadio, self.portcPin2OutputLowRadio, self.portcPin2InputHighImpRadio, self.portcPin2InputPullRadio],
                    [self.portcPin3OutputHighRadio, self.portcPin3OutputLowRadio, self.portcPin3InputHighImpRadio, self.portcPin3InputPullRadio],
                    [self.portcPin4OutputHighRadio, self.portcPin4OutputLowRadio, self.portcPin4InputHighImpRadio, self.portcPin4InputPullRadio],
                    [self.portcPin5OutputHighRadio, self.portcPin5OutputLowRadio, self.portcPin5InputHighImpRadio, self.portcPin5InputPullRadio],
                    [self.portcPin6OutputHighRadio, self.portcPin6OutputLowRadio, self.portcPin6InputHighImpRadio, self.portcPin6InputPullRadio],
                    [self.portcPin7OutputHighRadio, self.portcPin7OutputLowRadio, self.portcPin7InputHighImpRadio, self.portcPin7InputPullRadio]
                ],
            #PORTD
                [
                    [self.portdPin0OutputHighRadio, self.portdPin0OutputLowRadio, self.portdPin0InputHighImpRadio, self.portdPin0InputPullRadio],
                    [self.portdPin1OutputHighRadio, self.portdPin1OutputLowRadio, self.portdPin1InputHighImpRadio, self.portdPin1InputPullRadio],
                    [self.portdPin2OutputHighRadio, self.portdPin2OutputLowRadio, self.portdPin2InputHighImpRadio, self.portdPin2InputPullRadio],
                    [self.portdPin3OutputHighRadio, self.portdPin3OutputLowRadio, self.portdPin3InputHighImpRadio, self.portdPin3InputPullRadio],
                    [self.portdPin4OutputHighRadio, self.portdPin4OutputLowRadio, self.portdPin4InputHighImpRadio, self.portdPin4InputPullRadio],
                    [self.portdPin5OutputHighRadio, self.portdPin5OutputLowRadio, self.portdPin5InputHighImpRadio, self.portdPin5InputPullRadio],
                    [self.portdPin6OutputHighRadio, self.portdPin6OutputLowRadio, self.portdPin6InputHighImpRadio, self.portdPin6InputPullRadio],
                    [self.portdPin7OutputHighRadio, self.portdPin7OutputLowRadio, self.portdPin7InputHighImpRadio, self.portdPin7InputPullRadio]
                ]
            ]

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def showFileChooser(self, mode):
        if mode == 'LOAD':
            filename, filter = QFileDialog.getOpenFileName(None, 'Load Config From XML File', '.\\', '*.xml')
        elif mode == 'SAVE':
            filename, filter = QFileDialog.getSaveFileName(None, 'Save Config From XML File', '.\\', '*.xml')
        elif mode == 'GENERATE':
            filename, filter = QFileDialog.getSaveFileName(None, 'Generate Config To Header File', '.\\', '*.h')
        if filename == '':
            print('didn\'t select')
            return 'NULL'
        return filename
    
    def setDefaultConfig(self):
        for port in range(4):
            for pin in range(8):
                self.listOfRadios[port][pin][1].setChecked(True)
    
    def writeUserConfig(self, filename):
        listPort = ['PORTA', 'PORTB', 'PORTC', 'PORTD']
        name = filename.split('/')[-1].split('.')[0].upper() + '_H'
        
        configFile = open(filename, 'w')
        configFile.write("/*************************************************/\n")
        configFile.write("//            Configuration File\n\n")
        configFile.write("//    File Name: " + filename.split('/')[-1] + "\n")
        configFile.write("//    Date Modified: " + str(date.today().strftime("%B %d, %Y")) + "\n")
        configFile.write("//    Author: " + os.getlogin() + "\n")
        configFile.write("//    Generated by: GUI Configurator made by Ibrahim Saad\n")
        configFile.write("/*************************************************/\n\n\n")
        configFile.write("#ifndef " + name + "\n#define " + name + '\n\n\n')
        configFile.write('#define DIO_OUTPUT_LOW_PIN          0\n#define DIO_OUTPUT_HIGH_PIN         1\n#define DIO_INPUT_HIGH_IMP_PIN      2\n#define DIO_INPUT_PULL_UP_PIN       3\n\n')
        
        for port in range(4):
            configFile.write('\n/* ' + listPort[port] + ' */\n\n')
            for pin in range(8):
                if self.listOfRadios[port][pin][0].isChecked():
                    configFile.write('#define DIO_' + listPort[port] + '_PIN_' + str(pin) + '      DIO_OUTPUT_HIGH_PIN\n')
                if self.listOfRadios[port][pin][1].isChecked():
                    configFile.write('#define DIO_' + listPort[port] + '_PIN_' + str(pin) + '      DIO_OUTPUT_LOW_PIN\n')
                if self.listOfRadios[port][pin][2].isChecked():
                    configFile.write('#define DIO_' + listPort[port] + '_PIN_' + str(pin) + '      DIO_INPUT_HIGH_IMP_PIN\n')
                if self.listOfRadios[port][pin][3].isChecked():
                    configFile.write('#define DIO_' + listPort[port] + '_PIN_' + str(pin) + '      DIO_INPUT_PULL_UP_PIN\n')
        
        configFile.write('\n\n#endif   /* ' + name + ' */')
        configFile.close()
    
    def loadConfigFromXml(self, filename):
        doc = ET.parse(filename)
        root = doc.getroot()
        ports = ['PORTA', 'PORTB', 'PORTC', 'PORTD']
        for port in range(4):
            if root[port].tag == ports[port]:
                print(root[port].tag)
                i = 0
                for pin in root[port]:
                    if pin.tag == (ports[port][-1]+'_'+'PIN'+pin.tag[-1]):
                        print(pin.text)
                        if pin.text == ' OUT_H ':
                            self.listOfRadios[port][i][0].setChecked(True)
                        elif pin.text == ' OUT_L ':
                            self.listOfRadios[port][i][1].setChecked(True)
                        elif pin.text == ' IN_H_IMP ':
                            self.listOfRadios[port][i][2].setChecked(True)
                        elif pin.text == ' IN_P ':
                            self.listOfRadios[port][i][3].setChecked(True)
                        else:
                            print('ERROR: For PIN'+ str(i) +' file modified from another source and not the program')
                        i = i + 1
                    else:
                        print('ERROR: File modified from another source and not the program')
                        break
            else:
                print('ERROR: File modified from another source and not the program')
                break

    #Only this function is from stackoverflow (I didn't write it)
    def prettify(self, element, indent='  '):
        queue = [(0, element)]  # (level, element)
        while queue:
            level, element = queue.pop(0)
            children = [(level + 1, child) for child in list(element)]
            if children:
                element.text = '\n' + indent * (level+1)  # for child open
            if queue:
                element.tail = '\n' + indent * queue[0][0]  # for sibling open
            else:
                element.tail = '\n' + indent * (level-1)  # for parent close
            queue[0:0] = children  # prepend so children come before siblings

    def saveConfigToXml(self, filename):
        ports = ['PORTA', 'PORTB', 'PORTC', 'PORTD']
        root = ET.Element('PORTS')
        for port in range(4):
            portx = ET.SubElement(root, ports[port])
            for pin in range(8):
                portxPinx = ET.SubElement(portx, ports[port][-1] + '_PIN' + str(pin))
                if self.listOfRadios[port][pin][0].isChecked():
                    portxPinx.text = ' OUT_H '
                if self.listOfRadios[port][pin][1].isChecked():
                    portxPinx.text = ' OUT_L '
                if self.listOfRadios[port][pin][2].isChecked():
                    portxPinx.text = ' IN_H_IMP '
                if self.listOfRadios[port][pin][3].isChecked():
                    portxPinx.text = ' IN_P '
        self.prettify(root)
        tree = ET.ElementTree(root)
        #os.chmod(filename, stat.S_IWRITE)
        tree.write(filename, encoding='UTF-8', xml_declaration=True)
        #os.chmod(filename, stat.S_IREAD)

    def btnGenerateAction(self):
        filename = self.showFileChooser('GENERATE')
        if filename == 'NULL':
            print('File not choosen!, no action will be done')
            return
        self.writeUserConfig(filename)
        print('Done :), have a nice day')
    
    def btnLoadConfigAction(self):
        filename = self.showFileChooser('LOAD')
        if filename == 'NULL':
            print('File not choosen!, no action will be done')
            return
        self.loadConfigFromXml(filename)
        print('Done :), have a nice day')

    def btnSaveConfigAction(self):
        filename = self.showFileChooser('SAVE')
        if filename == 'NULL':
            print('File not choosen!, no action will be done')
            return
        self.saveConfigToXml(filename)
        print('Done :), have a nice day')

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"AVR DIO Donfigurator Tool", None))
        self.portaPin0Box.setTitle(QCoreApplication.translate("Form", u"PIN 0", None))
        self.portaPin0OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin0InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin0InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin0OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin1Box.setTitle(QCoreApplication.translate("Form", u"PIN 1", None))
        self.portaPin1OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin1InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin1InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin1OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin2Box.setTitle(QCoreApplication.translate("Form", u"PIN 2", None))
        self.portaPin2OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin2InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin2InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin2OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin3Box.setTitle(QCoreApplication.translate("Form", u"PIN 3", None))
        self.portaPin3OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin3InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin3InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin3OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin7Box.setTitle(QCoreApplication.translate("Form", u"PIN 7", None))
        self.portaPin7OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin7InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin7InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin7OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin4Box.setTitle(QCoreApplication.translate("Form", u"PIN 4", None))
        self.portaPin4OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin4InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin4InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin4OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin6Box.setTitle(QCoreApplication.translate("Form", u"PIN 6", None))
        self.portaPin6OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin6InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin6InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin6OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portaPin5Box.setTitle(QCoreApplication.translate("Form", u"PIN 5", None))
        self.portaPin5OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portaPin5InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portaPin5InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portaPin5OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portsForm.setItemText(self.portsForm.indexOf(self.portaPage), QCoreApplication.translate("Form", u"PORTA", None))
        self.portbPin5Box.setTitle(QCoreApplication.translate("Form", u"PIN 5", None))
        self.portbPin5OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin5InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin5InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin5OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin2Box.setTitle(QCoreApplication.translate("Form", u"PIN 2", None))
        self.portbPin2OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin2InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin2InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin2OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin7Box.setTitle(QCoreApplication.translate("Form", u"PIN 7", None))
        self.portbPin7OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin7InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin7InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin7OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin6Box.setTitle(QCoreApplication.translate("Form", u"PIN 6", None))
        self.portbPin6OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin6InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin6InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin6OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin4Box.setTitle(QCoreApplication.translate("Form", u"PIN 4", None))
        self.portbPin4OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin4InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin4InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin4OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin3Box.setTitle(QCoreApplication.translate("Form", u"PIN 3", None))
        self.portbPin3OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin3InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin3InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin3OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin0Box.setTitle(QCoreApplication.translate("Form", u"PIN 0", None))
        self.portbPin0OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin0InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin0InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin0OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portbPin1Box.setTitle(QCoreApplication.translate("Form", u"PIN 1", None))
        self.portbPin1OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portbPin1InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portbPin1InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portbPin1OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portsForm.setItemText(self.portsForm.indexOf(self.portbPage), QCoreApplication.translate("Form", u"PORTB", None))
        self.portcPin1Box.setTitle(QCoreApplication.translate("Form", u"PIN 1", None))
        self.portcPin1OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin1InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin1InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin1OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin4Box.setTitle(QCoreApplication.translate("Form", u"PIN 4", None))
        self.portcPin4OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin4InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin4InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin4OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin3Box.setTitle(QCoreApplication.translate("Form", u"PIN 3", None))
        self.portcPin3OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin3InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin3InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin3OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin6Box.setTitle(QCoreApplication.translate("Form", u"PIN 6", None))
        self.portcPin6OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin6InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin6InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin6OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin7Box.setTitle(QCoreApplication.translate("Form", u"PIN 7", None))
        self.portcPin7OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin7InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin7InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin7OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin2Box.setTitle(QCoreApplication.translate("Form", u"PIN 2", None))
        self.portcPin2OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin2InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin2InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin2OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin0Box.setTitle(QCoreApplication.translate("Form", u"PIN 0", None))
        self.portcPin0OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin0InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin0InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin0OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portcPin5Box.setTitle(QCoreApplication.translate("Form", u"PIN 5", None))
        self.portcPin5OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portcPin5InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portcPin5InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portcPin5OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portsForm.setItemText(self.portsForm.indexOf(self.portcPage), QCoreApplication.translate("Form", u"PORTC", None))
        self.btnLoad.setText(QCoreApplication.translate("Form", u"Load...", None))
        self.btnSave.setText(QCoreApplication.translate("Form", u"Save...", None))
        self.portdPin5Box.setTitle(QCoreApplication.translate("Form", u"PIN 5", None))
        self.portdPin5OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin5InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin5InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin5OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin4Box.setTitle(QCoreApplication.translate("Form", u"PIN 4", None))
        self.portdPin4OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin4InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin4InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin4OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin3Box.setTitle(QCoreApplication.translate("Form", u"PIN 3", None))
        self.portdPin3OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin3InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin3InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin3OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin0Box.setTitle(QCoreApplication.translate("Form", u"PIN 0", None))
        self.portdPin0OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin0InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin0InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin0OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin1Box.setTitle(QCoreApplication.translate("Form", u"PIN 1", None))
        self.portdPin1OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin1InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin1InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin1OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin7Box.setTitle(QCoreApplication.translate("Form", u"PIN 7", None))
        self.portdPin7OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin7InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin7InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin7OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin6Box.setTitle(QCoreApplication.translate("Form", u"PIN 6", None))
        self.portdPin6OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin6InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin6InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin6OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.portdPin2Box.setTitle(QCoreApplication.translate("Form", u"PIN 2", None))
        self.portdPin2OutputLowRadio.setText(QCoreApplication.translate("Form", u"OUTPUT LOW", None))
        self.portdPin2InputHighImpRadio.setText(QCoreApplication.translate("Form", u"INPUT HIGH IMP", None))
        self.portdPin2InputPullRadio.setText(QCoreApplication.translate("Form", u"INPUT PULL UP", None))
        self.portdPin2OutputHighRadio.setText(QCoreApplication.translate("Form", u"OUTPUT HIGH", None))
        self.btnGenerate.setText(QCoreApplication.translate("Form", u"Generate...", None))
        self.portsForm.setItemText(self.portsForm.indexOf(self.portdPage), QCoreApplication.translate("Form", u"PORTD", None))
    # retranslateUi

def main():
    app = QApplication(sys.argv)
    Widget = QWidget()
    Form = Ui_Form()
    Form.setupUi(Widget)
    Widget.show()
    Form.setDefaultConfig()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()