/*************************************************/
//            Configuration File

//    File Name: sample_header_test_gen.h
//    Date Modified: January 22, 2023
//    Author: ibrahim
//    Generated by: GUI Configurator made by Ibrahim Saad
/*************************************************/


#ifndef SAMPLE_HEADER_TEST_GEN_H
#define SAMPLE_HEADER_TEST_GEN_H


#define DIO_OUTPUT_LOW_PIN          0
#define DIO_OUTPUT_HIGH_PIN         1
#define DIO_INPUT_HIGH_IMP_PIN      2
#define DIO_INPUT_PULL_UP_PIN       3


/* PORTA */

#define DIO_PORTA_PIN_0      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTA_PIN_1      DIO_OUTPUT_LOW_PIN
#define DIO_PORTA_PIN_2      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTA_PIN_3      DIO_INPUT_PULL_UP_PIN
#define DIO_PORTA_PIN_4      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTA_PIN_5      DIO_OUTPUT_LOW_PIN
#define DIO_PORTA_PIN_6      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTA_PIN_7      DIO_INPUT_PULL_UP_PIN

/* PORTB */

#define DIO_PORTB_PIN_0      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTB_PIN_1      DIO_OUTPUT_LOW_PIN
#define DIO_PORTB_PIN_2      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTB_PIN_3      DIO_INPUT_PULL_UP_PIN
#define DIO_PORTB_PIN_4      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTB_PIN_5      DIO_OUTPUT_LOW_PIN
#define DIO_PORTB_PIN_6      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTB_PIN_7      DIO_INPUT_PULL_UP_PIN

/* PORTC */

#define DIO_PORTC_PIN_0      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTC_PIN_1      DIO_OUTPUT_LOW_PIN
#define DIO_PORTC_PIN_2      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTC_PIN_3      DIO_INPUT_PULL_UP_PIN
#define DIO_PORTC_PIN_4      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTC_PIN_5      DIO_OUTPUT_LOW_PIN
#define DIO_PORTC_PIN_6      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTC_PIN_7      DIO_INPUT_PULL_UP_PIN

/* PORTD */

#define DIO_PORTD_PIN_0      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTD_PIN_1      DIO_OUTPUT_LOW_PIN
#define DIO_PORTD_PIN_2      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTD_PIN_3      DIO_INPUT_PULL_UP_PIN
#define DIO_PORTD_PIN_4      DIO_OUTPUT_HIGH_PIN
#define DIO_PORTD_PIN_5      DIO_OUTPUT_LOW_PIN
#define DIO_PORTD_PIN_6      DIO_INPUT_HIGH_IMP_PIN
#define DIO_PORTD_PIN_7      DIO_INPUT_PULL_UP_PIN


#endif   /* SAMPLE_HEADER_TEST_GEN_H */